#!/bin/sh /etc/rc.common

START=85

start() {        
        echo start
        /usr/bin/overture-linux-mipsle -c /etc/overture/config.json -p 2 -l /var/log/overture.log >/dev/null 2>&1 &
	/usr/share/overture/otcheck.sh &
        # commands to launch application
}                 

stop() {          
        echo stop
	kill `ps | grep otcheck.sh | grep -v grep | awk '{ print $1 }'`
        killall overture-linux-mipsle
        # commands to kill application
}

